// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETD_Lab5.Models;

namespace NETD_Lab5.Migrations
{
    [DbContext(typeof(PromptContext))]
    [Migration("20201203232740_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NETD_Lab5.Models.CompletedPrompts", b =>
                {
                    b.Property<int>("completed_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("author_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("book_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_id")
                        .HasColumnType("int");

                    b.Property<int?>("promptsp_id")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.HasKey("completed_id");

                    b.HasIndex("promptsp_id");

                    b.ToTable("CompletedPrompts");
                });

            modelBuilder.Entity("NETD_Lab5.Models.Prompts", b =>
                {
                    b.Property<int>("p_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("p_id");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("NETD_Lab5.Models.CompletedPrompts", b =>
                {
                    b.HasOne("NETD_Lab5.Models.Prompts", "prompts")
                        .WithMany()
                        .HasForeignKey("promptsp_id");
                });
#pragma warning restore 612, 618
        }
    }
}
